import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { ContextTheme } from "./component/ThemeContext";
import Sidebar from "./component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextTheme>

          <div className="flex flex-row">
            <div>
            <Sidebar/>
            </div>
            
            <div>
              <div className="z-30 sticky top-0 flex">
                <Navbar/>
              </div>
              {children}
            </div>
          </div>
        </ContextTheme>
        </body>
    </html>
  );
}
